### ISSUE TITLE
Autoclicker isn't working

### ISSUE THREAD

**Issue by Kraker01** [ivanlay/pokeclicker-automator#1]
Hi, 

i'm using Firefox 89.0.2, latest Violent Monkey extension (v2.13.0), installed your script and using it on https://www.pokeclicker.com/

but it isn't working. Maybe the site has been updated?

**Comment by bigintersmind** [comment]
It's still working fine on my end, even after refreshing the game. Is it opening chests and starting boss fights in the dungeon or doing nothing at all?
