### ISSUE TITLE
Consider updating or...

### ISSUE THREAD

**Issue by MirandaDufrane** [ivanlay/pokeclicker-automator#4]
Hello. I've been looking at your link every single day to see if ANYONE has updates for this version of PokeClicker https://zocke1r.github.io/pokeclicker/
Or if maybe you could update it to the current version? Not a lot of people know how to code, me included. I've tried to contact people on this matter but I'm either ignored or no one is online. I've tried with discord and I only got belittled about the subject. I play PokeClicker on my phone, and as you can guess, I can't access any script/script's. I have this page watched to see if there are ANY updates at all. PLEASE let me know my messaging me on Reddit or on here somehow if you can do something about this or if I'm just wasting my time. Thank you. And sorry I put this in the "issues" section, I'm extremely new to GitHub.

>

**Comment by bigintersmind** [comment]
That link doesn't seem to work. We probably won't update this script to work with other versions of the game.
